# Generated by Django 3.0 on 2019-12-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='title',
        ),
    ]
